spec/index.spec.ts

Started tests to confirm usage through require.
Using the library through require (as [noted in docs](https://firebase.google.com/docs/functions/unit-testing) and [the examples](https://github.com/firebase/functions-samples/blob/master/quickstarts/uppercase/functions/test/test.offline.js)) should be tested. It appears that all current tests only load src directly (never from top level index to confirm exports).
Using like this should work:
```js
// At the top of test/index.test.js
const test = require('firebase-functions-test')();
test.mockConfig({ some: { config: '' } });
test.wrap(myFunctions.makeUppercase);
```

Start tests for index exports (all currently fail)

---

spec/app.spec.ts
spec/index.spec.ts
spec/lifecycle.spec.ts
src/index.ts

Fix 2 bugs in index.ts:
- top level export was actually missing the service account path parameter, which the init function in lifecycle.ts has.
- the cleanup function didn't work properly

Fix bug where setting service account key file location wasn't working

---

src/providers/firestore.ts

Closes #24
This PR is to add serialisation support for `firestore.Timestamp` and `DocumentReference` for use in `makeDocumentSnapshot`.
This fills in the gaps of functionality for the following:
- Online tests can now be written for Firestore functions  that need to receive a `DocumentReference` as part of the `DocumentSnapshot`
- `firestore.Timestamp` can now be used instead of just `Date`. This is very useful when defining interfaces and models in TS where setting a timestamp had to use `Date`, but when getting the timestamp from the database would be `firestore.Timestamp`;
Tests are passing however I haven't added any new tests; There's currently no coverage for this part of the package.

Added support for Timestamp and DocumentReference

---

src/providers/storage.ts

Addresses #19, changes default bucket so you don't need to supply it on every `makeObjectMetadata` call.
```js
const fft = require("firebase-functions-test")({
// ...
storageBucket: "my-firebase-project-id.appspot.com"
});
fft.storage.makeObjectMetadata({
name: 'unit_tests/Amaze.png',
bucket: 'my-firebase-project-id.appspot.com',
contentType: 'image/png'
});
```
```js
const fft = require("firebase-functions-test")({
// ...
storageBucket: "my-firebase-project-id.appspot.com"
});
fft.storage.makeObjectMetadata({
name: 'unit_tests/Amaze.png',
contentType: 'image/png'
});
```

Changes "makeObjectMetadata" to default to FIREBASE_CONFIG bucket if bucket not provided. (#19)

---

spec/index.spec.ts
spec/main.spec.ts
spec/providers/https.spec.ts
src/main.ts

Adds support for `https.onCall` functions and improves filtering of `https.onRequest` functions.
**Do not merge!** I'm not sure if there are other aspects of this I'm missing. I'm not sure if there's any value to adding `providers/https.ts` other than to allow `onCall` support to be discoverable in the library. Since the bundles passed to the functions are arbitrary JSON I'm not sure what help we could be.
Let me know your thoughts!
See [providers/https.spec.ts](https://github.com/firebase/firebase-functions-test/blob/ah-oncall/spec/providers/https.spec.ts)

Adds `onCall` function support (#9)

---

src/providers/auth.ts

"console.log(new Date('2018-04-03T03:92:48Z'))" results in "Invalid Date" due to "92" not being a valid value for the number of minutes in an hour.

Changed lastSignInTime to be a valid date and time

---

.travis.yml
package.json
src/main.ts

I've been working on adding tests to [firebase/extensions](https://github.com/firebase/extensions) and when trying to wrap the function handlers used by Extensions (e.g. `functions.handler.firestore.document.onWrite`) it errors with `TypeError: Cannot read property 'match' of undefined` as the `eventType` key 'does' exist on the `defaultContext` object, but has an `undefined` value assigned.
This small PR adds an additional `undefined` check.
```js
export const fstranslate = functions.handler.firestore.document.onWrite(
async (change): Promise<void> => {
console.warn('Hello from inside my wrapped handler function.');
return;
});
// ...
import * as functionsTestInit from "firebase-functions-test";
// ...
let functionsTest = functionsTestInit();
// ...
const wrappedFn = …
```

fix(wrap): Extensions `functions.handler` -> `eventType` key exists but is `undefined` value

---

spec/providers/https.spec.ts
src/main.ts

Resolves https://github.com/firebase/firebase-functions-test/issues/41

Support rawRequest in callable context

---

README.md
package.json
spec/index.spec.ts
spec/providers/database.spec.ts
spec/providers/firestore.spec.ts
src/providers/database.ts

Add support for null value in data snapshot (https://github.com/firebase/firebase-functions-test/issues/48), added unit tests for creating Firestore DocumentSnapshot and RTDB DataSnapshot, also updated dependencies to more modern versions. (Note: peer dependencies are updated less aggressively than dev dependencies, since dev dependencies are what a contributor of this library must install, whereas peer dependencies are what users of this library must use)

Support null value in makeDataSnapshot and update dependencies

---

.prettierrc
.travis.yml
package.json
spec/index.spec.ts
spec/lifecycle.spec.ts
spec/main.spec.ts
spec/providers/database.spec.ts
spec/providers/firestore.spec.ts
spec/providers/https.spec.ts
src/app.ts
src/lifecycle.ts
src/main.ts
src/providers/analytics.ts
src/providers/auth.ts
src/providers/crashlytics.ts
src/providers/database.ts
src/providers/firestore.ts
src/providers/pubsub.ts
src/providers/storage.ts
tsconfig.json
tsconfig.release.json
tslint.json

I added prettier to the repo, and ran "npm run format:fix"

Add prettier to repo

---

spec/index.spec.ts
spec/providers/scheduled.spec.ts
src/main.ts

Adds support for scheduled functions that use only the `context` parameter when called.
Also includes tests.
```
const scheduledFunc = functions.pubsub.schedule('every 2 hours').onRun(async context => {
// Do something
});
require('firebase-functions-test').wrap(scheduledFunc)();
// Or with a context
require('firebase-functions-test').wrap(scheduledFunc)({ timestamp });
```

Support for scheduled functions

---

src/main.ts

As part of trying to test the extensions/firestore-bigquery-export module. We need to introduce the ability to set the resource key values (the types already support this, just this change is missing). Specifically, [this line](https://github.com/firebase/extensions/blob/next/firestore-bigquery-export/functions/src/index.ts#L45) will fail when using the function wrap helper with `cannot read property 'name' of undefined`. This change allows us to specify the resource values needed for the wrapped cloud function trigger.
```ts
const wrapped = functionsTest.wrap(require("../src/index").fsexportbigquery);
wrapped(docChange, {
eventId: "test",
resource: {
name: "test",
},
});
```

feat: `wrap` method now accepts `resource` as override in Context object.

---

.gitignore
package.json
spec/integration/providers/firestore.spec.ts
src/providers/firestore.ts

Added a function to clear all firestore data between tests. Similar to https://github.com/firebase/firebase-js-sdk/blob/master/packages/testing/src/api/index.ts#L233
This makes it easier to run tests in offline mode
```js
const test = require("firebase-functions-test")({
projectId: "project-id",
});
describe('test', () => {
afterEach(async () => {
await test.firestore.clearFirestoreData({ projectId: "project-id" });
});
it('test1', () => {
// test that involes database changes
});
it('test2', () => {
// test that involes database changes
});
});
```
in order to implement tests I think I would need change:
`"test": "mocha .tmp/spec/index.spec.js"` 
to
`"test": "firebase emulators:exec 'mocha .tmp/spec/index.spec.js'"`
I want to know if there is a better way to implement tests before I …

added method to clear all firestore data

---

spec/providers/database.spec.ts
src/providers/database.ts

Allow creation of `DataSnapshot`s for multiple RTDB instances.
Currently the only way to create a `DataSnapshot` for different RTDB instances is to create a `App` per instance.
```js
const snapshot = makeDataSnapshot({ hello: 'world' }, 'path', null, 'https://another-instance.firebaseio.com');
```

Allow RTDB instance to be specified when using makeDataSnapshot

---

CHANGELOG.md
package.json

Looks like we had something go wrong with a merge at some point - v0.2.1 has already been released, but package.json still showed 0.2.0.

Adds changelog for 0.2.2 and correct package.json version

---

spec/main.spec.ts
src/main.ts

**Description**
`functions.config()` parses ENV variable(s) only once and saves the value into a variable for later usage. Thus setting a new value to `process.env.CLOUD_RUNTIME_CONFIG` is not causing getting a recent value.
**Motivation**
Calling the `mockConfig` function multiple times with different configuration values makes writing unit tests easier and gives flexibility to the developer. What do you think?
P.S This topic has been already mentioned in #68.
**Code Sample**
```typescript
// spec/unit/auth-on-create.spec.ts
import test from 'firebase-functions-test';
const app = test();
describe('[Unit] Auth.onCreate()', () => {
afterEach(() => {
app.cleanup();
});
it('does something with config().foo', () => {
app.mockConfig({ foo: 'bar' });
...
});
it('does something with …
```

Remove functions.config.singleton

---

spec/providers/firestore.spec.ts

In #105 I was distracted and clicked to merge before addressing feedback. Sorry.

PR feedback from #105

---

src/providers/firestore.ts

Reviewing the geopoint bug I realized people complained that the error message called anything unserializeable a geopoint. This fixes that bug.

Improve error message for Firestore encoding errors

---

src/providers/firestore.ts

The `firebase-functions-test` repo was importing an undocumented path for a trivial 13LOC function. Rather than futz with public imports we'll just duplicate this 13LOC of code.

Vendor dateToTimestampProto

---

spec/main.spec.ts
src/main.ts
src/providers/firestore.ts

When running the function, the wrapper tries to extract the `EventContext` `params` from the triggered data based on the wildcard path.
E.g. A wildcard path of `users/{userId}` run against with `users/FOO` would result in `params: { userId: 'FOO' }`.
Provided `params` to the wrapped function are preferred over the extracted ones - I've only done this to prevent breaking usage for anyone whose not matching the values in the path up to the provided `params`.
Also added tests (and updated the `auth and authType` tests as they were just being run with junk data).
See the tests:
Firebase RTDB - https://github.com/bookcreator/firebase-functions-test/blob/params/spec/main.spec.ts#L150-L165
Firestore - https://github.com/bookcreator/firebase-functions-test/blob/params/spec/main.spec.ts#L167-L185

Try to extract context.params from triggered data

---

package.json
scripts/publish.sh

This commit is a copy of [firebase/firebase-functions#940](https://github.com/firebase/firebase-functions/pull/940).
* https://docs.npmjs.com/cli/v8/commands/npm-install
* https://docs.npmjs.com/cli/v8/commands/npm-ci

Use npm ci on publish scripts

---

spec/v2.spec.ts
src/cloudevent/partials/storage/index.ts

Storage CloudEvents contain a "bucket" field. The mock data should
return this "bucket" field to accurately reflect live data.
[More info here](https://github.com/firebase/firebase-functions/blob/27a49837ea7b74d9d2926e74c387f45704d57889/src/v2/providers/storage.ts#L185)

Add top-level bucket field to Mock Storage CloudEvents

---

.github/workflows/test.yaml
spec/main.spec.ts

This commit adds CI for firebase-functions-test as an additional level
of protection.
This is a duplicate of the {test.yaml from firebase-functions](https://github.com/firebase/firebase-functions/blob/master/.github/workflows/test.yaml)

Add CI for firebase-functions-test

---

spec/v2.spec.ts

This commit adds unit test for all the v2 spec items.
As commented, `id`, `time`, and a few others are generated at runtime.
In those instances the assertion does the no-op `thing: thing` check.
With this commit I feel comfortable moving forward with v2.1.0.
Test All The Things!!
*insert all the things meme here*

Write ALL the unit tests

---

spec/v2.spec.ts
src/cloudevent/generate.ts
src/cloudevent/mocks/database/helpers.ts
src/v2.ts

This commit updates the test sdk api for the Database CloudEventPartial
to support end-users submitting JSON that gets transformed into `DataSnapshot`
instead of forcing users to import and use `Change` and `DataSnapshot` to
mock out the CloudEvent resopnses.
```
// Previous example
const cloudFn = database.onValueDeleted(referenceOptions, handler);
const cloudFnWrap = wrapV2(cloudFn);
const dataVal = { snapshot: 'override' };
// Calling makeDataSnapshot is the step we are trying to simplify
const data = makeDataSnapshot(dataVal, referenceOptions.ref);
cloudFnWrap({ data: data });
```
```
// New example
const cloudFn = database.onValueDeleted(referenceOptions, handler);
const cloudFnWrap = wrapV2(cloudFn);
const dataVal = { snapshot: 'override' };
cloudFnWrap({ data: dataVal });
```

Update Rtdb test sdk to allow json for CloudEvent

---

src/main.ts
src/v1.ts

This PR fixes the typing of a wrapped function's second argument, namely: `options`. Such options are described by two types: `CallableContextOptions` and `EventContextOptions`. The first is only due to the `http.onCall()`, since the function `http.onRequest()` is not supposed to be wrapped. The latter is due to all other cloud functions under V1.
With the current implementation, the type of the options is the result of a union of both types mentioned above. Because of that, a consumer of this API was led to believe that some options due to a "event" function were available to "callable" function, and vice-versa.
This PR fixes that by conditionally assigning the type of such options depending on the function being wrapped.
There is no API change. But here is an example of what this PR …

Use conditional typing for defining the right set of options

---

package-lock.json
package.json
spec/v2.spec.ts
src/cloudevent/mocks/database/helpers.ts
src/cloudevent/mocks/helpers.ts
src/cloudevent/mocks/storage/index.ts

The api of the manifest changed in firebase-functions@3.23. Some inputs have been updated to be `T | Expression<T>`.
The api of the manifest changed in firebase-functions@3.23. Some inputs have been updated to be `T | Expression<T>`.

Support Params as inputs in eventTrigger

---

spec/main.spec.ts
src/v1.ts

V4 Functions SDK does not expose the config singleton directly.
Use the internal-only `resetCache` function instead.

Update mockConfig function for v4 firebase-functions

---

CHANGELOG.md
package.json

We also pin down peer dep requirement for firebase-admin to peer dependencies required for v4 firebase-functions sdk.

BREAKING: Drop support for Firebase Functions SDK v3 and below.

---

spec/main.spec.ts
spec/v2.spec.ts
src/cloudevent/mocks/database/helpers.ts
src/cloudevent/mocks/helpers.ts
src/v1.ts

1. Replace all use of __trigger annotation to __endpoint
2. Correct import path for Expression class/type.

Fix Firebase Functions v4 compatibility issues.

---

CHANGELOG.md
package.json

Reverts firebase/firebase-functions-test#174
Accidentally pushed to master branch instead of launch.next branch 🤦🏼 .

Revert "BREAKING: Drop support for Firebase Functions SDK v3 and below."

---

CHANGELOG.md
package.json

Redo https://github.com/firebase/firebase-functions-test/pull/174, targeting the correct `launch.next` branch.

BREAKING: Drop support for Firebase Functions SDK v3 and below - take 2

---

package-lock.json
package.json

This should fix all broken tests!

Bump firebase functions sdk version to v4 release candidate

---

CHANGELOG.md
package-lock.json
package.json
spec/main.spec.ts
spec/v2.spec.ts
src/cloudevent/mocks/database/helpers.ts
src/cloudevent/mocks/helpers.ts
src/v1.ts

* Drop support for Firebase Functions SDK v3 and below.
* Drop support for Firebase Admin SDK v7 and below.
The test SDK v2 works with Firebase Functions SDK v4 and above.

firebase-functions-test v3 (major version bump)

---

src/features.ts
src/index.ts

Right pull improves type definition for cleanup method.
Before:
```typescript
import firebase_function_test from 'firebase-functions-test';
const ffTest = firebase_function_test();
// eslint-disable-next-line @typescript-eslint/no-unsafe-call
ffTest.cleanup();
```
After
```typescript
import firebase_function_test from 'firebase-functions-test';
const ffTest = firebase_function_test();
ffTest.cleanup();
```

Improve cleanup type definition

---

.gitignore
package-lock.json
package.json
src/cloudevent/mocks/firestore/firestore-on-document-created-with-auth-context.ts
src/cloudevent/mocks/firestore/firestore-on-document-deleted-with-auth-context.ts
src/cloudevent/mocks/firestore/firestore-on-document-updated-with-auth-context.ts
src/cloudevent/mocks/firestore/firestore-on-document-written-with-auth-context.ts
src/cloudevent/mocks/firestore/helpers.ts
src/cloudevent/mocks/partials.ts

This PR aims to add support for testing new auth context triggers in Firestore

feat: auth context support

---

CHANGELOG.md

We forgot the changelog entry for #227. There are no other changes slated for release, so the publish workflow won't run with the changelog empty.

Add changelog entry for #227

---

.github/workflows/test.yaml
package-lock.json
package.json
spec/v2.spec.ts
src/main.ts
src/v2.ts

Closes #163
```ts
// src/index.ts
import { onCall } from "firebase-functions/v2/https";
export const helloWorld = onCall(request => {
return { message: "hello" };
});
```
```ts
// test/index.test.ts
import { helloWorld } from "../src/index";
describe("test", () => {
it('should work', () => {
const wf = wrap(helloWorld);
wf(req, res);
})
})
```

feat: add support for v2 callable functions

---

spec/providers/firestore.spec.ts
src/providers/firestore.ts

Remove hardcoded firestore hostname from clearFirestoreData function and make possibility to configure it via FIRESTORE_EMULATOR_HOST environment variable

fix(firestore): use hostname from env variable

---

.github/workflows/test.yaml

https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/#actions-cache-v1-v2-and-actions-toolkit-cache-package-closing-down

fix(workflows): update actions/cache to v4 as v1 obsolete
